#!/usr/bin/bash

set -oue pipefail

QUALIFIED_KERNEL="$(rpm -qa | grep -P 'kernel-cachyos-(\d+\.\d+\.\d+)' | sed -E 's/kernel-cachyos-//')"
/usr/libexec/rpm-ostree/wrapped/dracut --no-hostonly --kver "$QUALIFIED_KERNEL" --reproducible -v --add ostree -f "/lib/modules/$QUALIFIED_KERNEL/initramfs.img"

chmod 0600 /lib/modules/$QUALIFIED_KERNEL/initramfs.img