#!/usr/bin/env bash

# Script Version
VER=2
VER_FILE="/etc/quark/flatpak/flatpak_manager_version"
VER_RAN=$(cat $VER_FILE)

# Run script if updated
if [[ -f $VER_FILE && $VER = $VER_RAN ]]; then
  echo "Flatpak manager v$VER has already ran. Exiting..."
  exit 0
fi

# Opt out of and remove fedora flatpak repo
if grep -qz 'fedora' <<< $(flatpak remotes); then
  /usr/lib/fedora-third-party/fedora-third-party-opt-out
  /usr/bin/fedora-third-party disable
  flatpak remote-delete fedora --force
fi

# Ensure Flathub is enabled
flatpak remote-add --if-not-exists --system flathub /usr/etc/flatpak/remotes.d/flathub.flatpakrepo
flatpak remote-modify --system --enable flathub

# Flatpak theming support
flatpak override \
  --filesystem=xdg-config/gtk-4.0:ro \
  --filesystem=xdg-config/gtk-3.0:ro \
  --filesystem=xdg-data/icons:ro

# XInput for Firefox
flatpak override \
  --system \
  --env=MOZ_USE_XINPUT2=1 \
  org.mozilla.firefox

# Lists of flatpaks
FLATPAK_LIST=$(flatpak list --columns=application)
INSTALL_LIST=$(cat /usr/share/ublue-os/quark/flatpak/install)
REMOVE_LIST=$(cat /usr/share/ublue-os/quark/flatpak/remove)

# Remove flatpaks in list once
if [[ ! -f $VER_FILE && -n $REMOVE_LIST ]]; then
  flatpak --system remove -y ${REMOVE_LIST[@]}
fi

# Install flatpaks in list
if [[ -n $INSTALL_LIST ]]; then
  if ! flatpak --system install -y --or-update ${INSTALL_LIST[@]}; then
    # exit on error
    exit 1
  fi
fi

mkdir -p /etc/quark/flatpak
echo $VER > $VER_FILE
