name: build-quark-nvidia
on:
  workflow_run:
    workflows: ["build-quark"]
    types:
      - completed
  push:
    branches:
      - main
      - testing
    paths-ignore:
      - '**.md'

env:
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    USE_PERSONAL_REPO: false

jobs:
  push-ghcr:
    name: Create NVIDIA images
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image_flavor: [silverblue, kinoite]
        base_name: [quark-open, quark-closed]
        nvidia_version: [stable, beta]
        fedora_version: [42, 43]
        include:
          - fedora_version: 43
            is_latest_version: true
    steps: 
      - name: Define NVIDIA variables
        run: |
          if [[ "${{ matrix.base_name }}" == "quark-closed" ]]; then
              echo "NVIDIA_MODULE_TYPE=nvidia" >> $GITHUB_ENV
          else
              echo "NVIDIA_MODULE_TYPE=nvidia-open" >> $GITHUB_ENV
          fi

          if [[ "${{ github.ref_name }}" == "testing" ]]; then
            echo "QUARK_VERSION=${{ matrix.fedora_version }}-testing" >> $GITHUB_ENV
          else
            echo "QUARK_VERSION=${{ matrix.fedora_version }}" >> $GITHUB_ENV
          fi


      - name: Checkout
        uses: actions/checkout@v4

      - name: Matrix Variables
        run: |
          if [[ "${{ matrix.image_flavor }}" == "kinoite" ]]; then
            echo "IMAGE_NAME=${{ matrix.base_name }}-plasma" >> $GITHUB_ENV
            echo "BASE_IMAGE=ghcr.io/trgeiger/quark-plasma" >> $GITHUB_ENV
          else 
            echo "IMAGE_NAME=${{ matrix.base_name }}" >> $GITHUB_ENV
            echo "BASE_IMAGE=ghcr.io/trgeiger/quark" >> $GITHUB_ENV
          fi 
          echo "TARGET"="quark" >> $GITHUB_ENV

      - name: Generate tags
        id: generate-tags
        shell: bash
        run: |
          # Generate a timestamp for creating an image version history
          TIMESTAMP="$(date +%Y%m%d)"
          FEDORA_VERSION="${{ matrix.fedora_version }}"
          COMMIT_TAGS=()
          BUILD_TAGS=()
          # Have tags for tracking builds during pull request
          SHA_SHORT="${GITHUB_SHA::7}"
          COMMIT_TAGS+=("pr-${{ github.event.pull_request.number }}-${FEDORA_VERSION}-${{ matrix.nvidia_version }}")
          COMMIT_TAGS+=("${SHA_SHORT}-${FEDORA_VERSION}-${{ matrix.nvidia_version }}")

          if [[ ${{ github.ref_name }} == "testing" ]]; then
             BUILD_TAGS=("${FEDORA_VERSION}-${{ matrix.nvidia_version }}-testing" "${FEDORA_VERSION}-${{ matrix.nvidia_version }}-testing-${TIMESTAMP}")
             if [[ "${{ matrix.is_latest_version }}" == "true" ]]; then
                 BUILD_TAGS+=("testing-${{ matrix.nvidia_version }}")
                 echo "DEFAULT_TAG=testing-${{ matrix.nvidia_version }}" >> $GITHUB_ENV
             fi
          else
             BUILD_TAGS=("${FEDORA_VERSION}-${{ matrix.nvidia_version }}" "${FEDORA_VERSION}-${{ matrix.nvidia_version }}-${TIMESTAMP}")
             if [[ "${{ matrix.is_latest_version }}" == "true" ]]; then
                 BUILD_TAGS+=("latest-${{ matrix.nvidia_version }}")
                 echo "DEFAULT_TAG=latest-${{ matrix.nvidia_version }}" >> $GITHUB_ENV
             else
                 echo "DEFAULT_TAG=${FEDORA_VERSION}-${{ matrix.nvidia_version }}" >> $GITHUB_ENV
             fi
          fi

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              echo "Generated the following commit tags: "
              for TAG in "${COMMIT_TAGS[@]}"; do
                  echo "${TAG}"
              done
              alias_tags=("${COMMIT_TAGS[@]}")
          else
              alias_tags=("${BUILD_TAGS[@]}")
          fi
          echo "Generated the following build tags: "
          for TAG in "${BUILD_TAGS[@]}"; do
              echo "${TAG}"
          done
          echo "alias_tags=${alias_tags[*]}" >> $GITHUB_OUTPUT

      - name: Get Current Fedora Version
        id: labels
        run: |  
          ver=$(skopeo inspect docker://ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.QUARK_VERSION }} | jq -r '.Labels["org.opencontainers.image.version"]')
          echo "VERSION=$ver" >> $GITHUB_OUTPUT

      # Build metadata
      - name: Image Metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.version=${{ steps.labels.outputs.VERSION }}
            org.opencontainers.image.description=Personal Silverblue image with NVIDIA drivers

      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
          remove-large-packages: true
          remove-cached-tools: true
          remove-swapfile: true

      - name: Retrieve akmods signing key
        run: |
          mkdir -p tmp

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              echo "Not using signing key"
          else
              echo "${{ secrets.QUARK_PRIVKEY_18012024 }}" > tmp/private_key.priv
          fi

      - name: Pull images
        uses: Wandalen/wretry.action@v3.5.0
        with:
          attempt_limit: 3
          attempt_delay: 15000
          command: |
            podman pull ${{ env.BASE_IMAGE }}:${{ env.QUARK_VERSION }}
            podman pull ${{ env.IMAGE_REGISTRY }}/nvidia-kmod-${{ env.NVIDIA_MODULE_TYPE }}:${{ matrix.fedora_version }}-${{ matrix.nvidia_version }}

      # Build image using Buildah action
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2.13
        with:
          containerfiles: |
            ./Containerfile.nvidia
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ steps.generate-tags.outputs.alias_tags }}
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            BASE_IMAGE_NAME=${{ matrix.image_flavor }}
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            IMAGE_VENDOR=${{ github.repository_owner }}
            QUARK_VERSION=${{ env.QUARK_VERSION }}
            KMOD_IMAGE_VERSION=${{ matrix.fedora_version }}
            NVIDIA_VERSION=${{ matrix.nvidia_version }}
            NVIDIA_MODULE_TYPE=${{ env.NVIDIA_MODULE_TYPE }}
            USE_PERSONAL_REPO=${{ env.USE_PERSONAL_REPO }}
          labels: ${{ steps.meta.outputs.labels }}
          oci: false
          extra-args: |
            --target=${{ env.TARGET }}

      - name: Sign kernel
        uses: EyeCantCU/kernel-signer@v0.2.1
        with:
          image: ${{ steps.build_image.outputs.image }}
          default-tag: ${{ env.DEFAULT_TAG }}
          privkey: ${{ secrets.QUARK_PRIVKEY_18012024 }}
          pubkey: /etc/pki/akmods/certs/quark-secure-boot.der
          tags: ${{ steps.build_image.outputs.tags }}
          kernel_suffix: cachyos

      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: Wandalen/wretry.action@v3.5.0
        id: push
        if: github.event_name != 'pull_request'
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          action: redhat-actions/push-to-registry@v2
          attempt_limit: 3
          attempt_delay: 15000
          with: |
            image: ${{ steps.build_image.outputs.image }}
            tags: ${{ steps.build_image.outputs.tags }}
            registry: ${{ steps.registry_case.outputs.lowercase }}
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
            extra-args: |
              --disable-content-trust

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  

      - uses: sigstore/cosign-installer@main
        if: github.event_name != 'pull_request'

      - name: Sign the container image
        if: github.event_name != 'pull_request'
        run: cosign sign -y ${{ steps.registry_case.outputs.lowercase }}/${{ env.IMAGE_NAME }}@${DIGEST}
        env:
          DIGEST: ${{ fromJSON(steps.push.outputs.outputs).digest }}

      # - name: Verify the pushed tags
      #   if: github.event_name != 'pull_request' && github.ref_name != 'testing'
      #   run: |
      #       cosign verify ${{ steps.registry_case.outputs.lowercase }}/${{ env.IMAGE_NAME }} \
      #       --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
      #       --certificate-identity-regexp "${{ github.server_url }}/${{ github.repository }}"

      - name: Echo outputs
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ toJSON(steps.push.outputs.outputs) }}"
